/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LibraryVisitorsTrackingSystem;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;  
import java.sql.ResultSetMetaData;
import javax.swing.JTextField;

/**
 *
 * @author jober
 */
public class Admin_Gui extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Gui
     */
    public Admin_Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminenter_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Admin_key = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Talisay City College Library Department");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 423, 31));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Key:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        adminenter_btn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        adminenter_btn.setText("Enter");
        adminenter_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminenter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminenter_btnActionPerformed(evt);
            }
        });
        jPanel1.add(adminenter_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 62, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 60, 20));

        Admin_key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_keyActionPerformed(evt);
            }
        });
        jPanel1.add(Admin_key, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 140, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("WELCOME!!");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 100, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryVisitorsTrackingSystem/logo.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 100, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryVisitorsTrackingSystem/Ha.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void adminenter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminenter_btnActionPerformed
        // TODO add your handling code here:  
    Connection con;
      PreparedStatement ps;
       
            
            String adminKey = Admin_key.getText();
        boolean status = true;     
                                
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           
            String jdbcURL = "jdbc:mysql://127.0.0.1:3306/tcclibrarydb?autoReconnect=true&useSSL=false";
            String username = "root";
            String password = "";

            
            con = DriverManager.getConnection(jdbcURL, username, password);
            
           
            ps = con.prepareStatement("SELECT * FROM admin_db;");
            ResultSet rs = ps.executeQuery();
               
           int num1 = 1; //num1 and num2 is an identifier used to disable looping of rs.next
           int num2 = 1;
            while (rs.next()){ //rs.next is true 
                if (adminKey.equals(rs.getString("admin_key")) ){                            
                      dashboard_Gui dashboard = new dashboard_Gui();
                      dashboard.setVisible(true);
                      this.dispose();
                    this.dispose();

                    num1 +=1;
                    break;
                }
                else{  
                    status = false;
                    num1++;
                    num2++;

                }
            }
                if(num1 == num2){ //prevent show message to pop up multiple times
                     JOptionPane.showMessageDialog(this, "username or password doesnt match!");
                    }
            
           
            
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Admin_Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          catch (SQLException ex) {
            Logger.getLogger(Admin_Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_adminenter_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu_Gui menu = new Menu_Gui();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Admin_keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_keyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Admin_keyActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Admin_key;
    private javax.swing.JButton adminenter_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
